language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-22
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

notifications:
  email: false

before_install:
  - chmod +x gradlew
  - export TERM=dumb

script: ./gradlew assembleDebug
