language: android
jdk: oraclejdk7

android:
  components:
    # The BuildTools version used by project
    - build-tools-21.1.2
    # The SDK version used to compile project
    - android-22

notifications:
  email: false

before_install:
  - chmod +x gradlew
  - export TERM=dumb

script: ./gradlew clean build
